---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: !format Applications/container-demo/%BUILD_NUMBER%
  type: udm.DeploymentPackage
  deployables:
  - name: mysql
    type: k8s.ResourcesFile
    createOrder: "61"
    file: !file "artifacts/mysql.yaml"
    tags:
    - gke
  - name: app
    type: k8s.ResourcesFile
    createOrder: "62"
    file: !file "artifacts/app.yaml"
    tags:
    - gke
    - oks
  - name: ingress
    type: k8s.ResourcesFile
    createOrder: "62"
    file: !file "artifacts/gke_ingress.yaml"
    tags:
    - gke
  - name: oks_route
    type: k8s.ResourcesFile
    createOrder: "62"
    file: !file "artifacts/oks_route.yaml"
    tags:
    - oks
  - name: oks_petclinic_ns
    type: k8s.NamespaceSpec
    namespaceName: petclinic
    tags:
    - oks
  - name: gke_petclinic_ns
    type: k8s.NamespaceSpec
    namespaceName: petclinic
    tags:
    - gke
