xld:
  image: xebialabs/xl-deploy:9.7.2
  #volumes:
  # - ~/xl-licenses/deployit-license.lic:/opt/xebialabs/xl-deploy-server/conf/deployit-license.lic
  links:
   - socat
  ports:
   - "4516:4516"
  environment:
    - ADMIN_PASSWORD=admin
    - ACCEPT_EULA=Y
xlr:
  image: xebialabs/xl-release:9.7.2
  #volumes:
  # - ~/xl-licenses/xl-release-license.lic:/opt/xebialabs/xl-release-server/conf/xl-release-license.lic
  links:
   - jenkins
   - xld
   - socat
  ports:
   - "5516:5516"
  environment:
    - ADMIN_PASSWORD=admin
    - ACCEPT_EULA=Y

socat:
  image: bobrik/socat
  ports:
    - "2376:2375"
  privileged: true
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  command: TCP4-LISTEN:2375,fork,reuseaddr UNIX-CLIENT:/var/run/docker.sock

jenkins:
  image: xebialabsunsupported/docker-jenkins:2.189-alpine
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
  links:
   - xld
   - socat
  ports:
   - "8080:8080"