---
apiVersion: xl-deploy/v1
kind: Infrastructure
spec:
- name: Infrastructure/gke_playground
  type: k8s.Master
  tags:
  - gke
  apiServerURL: !value Infrastructure_gke_playground_apiServerURL
  caCert: !value Infrastructure_gke_playground_caCert
  tlsCert: !value Infrastructure_gke_playground_tlsCert
  tlsPrivateKey: !value Infrastructure_gke_playground_tlsPrivateKey
  debug: true
- name: Infrastructure/docker_desktop_k8s
  type: k8s.Master
  tags:
  - local
  apiServerURL: !value Infrastructure_docker_desktop_k8s_apiServerURL
  caCert: !value Infrastructure_docker_desktop_k8s_caCert
  tlsCert: !value Infrastructure_docker_desktop_k8s_tlsCert
  tlsPrivateKey: !value Infrastructure_docker_desktop_k8s_tlsPrivateKey
  debug: true